### ISSUE TITLE
KtTable: Re-think API & Re-write Completely

### ISSUE THREAD

**Issue by mvangent** [3YOURMIND/kotti#163] opened 2020-03-06 13:39 UTC
**Describe the bug**
Table hacks need to be standardised into a structured solution. @carsoli can you provide a list of your findings in this issue? 
**To Reproduce**

to be implemented

**Comment by FlorianWendelborn** [comment] 2021-02-02 16:44
Closed due to #350 being basically a newer duplicate of this.

**Closed by FlorianWendelborn** 2021-02-02 16:44 UTC
Labels: priority:4-high, type:enhancement, type:refactor
